spring:
  application:
    name: deliver-bills
  datasource:
    url: jdbc:postgresql://89.116.73.41:6969/deliver-bills
    username: postgres
    password: WiN6MjcjVsOnMnZZJGZeajc7cDcl
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 100 # ms
      connection-timeout: 10000 # 10s
      max-lifetime: 120000 # 2m
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  config: classpath:log4j2.xml